### ISSUE TITLE
Parsing for prettier broken on .gts files

### ISSUE THREAD

**Issue by vlascik** [embroider-build/content-tag#85]
```
> node_modules\.bin\prettier scratches\repro1.gts
  
  [warn] Ignored unknown option { editorconfig: true }.
scratches/repro1.gts
  [error] scratches/repro1.gts: RuntimeError: unreachable
  [error]     at wasm://wasm/00467e76:wasm-function[544]:0x960f5
  [error]     at wasm://wasm/00467e76:wasm-function[1667]:0xc3bf8
  [error]     at wasm://wasm/00467e76:wasm-function[696]:0xa19d8
  [error]     at wasm://wasm/00467e76:wasm-function[298]:0x753e0
  [error]     at wasm://wasm/00467e76:wasm-function[1607]:0xc1ff2
  [error]     at Preprocessor.parse (P:\Project\node_modules\content-tag\pkg\node\content_tag.cjs:234:26)
[error]     at codeToGlimmerAst (file:///P:/Project/node_modules/prettier-plugin-ember-template-tag/dist/prettier-plugin-ember-template-tag.js:70078:26)
[error]     at preprocess (file:///P:/Project/node_modules/prettier-plugin-ember-template-tag/dist/prettier-plugin-ember-template-tag.js:70060:22)
[error]     at Object.parse (file:///P:/Project/node_modules/prettier-plugin-ember-template-tag/dist/prettier-plugin-ember-template-tag.js:70070:26)
[error]     at parse4 (file:///P:/Project/node_modules/prettier/index.mjs:20685:24)
```

```ts
// repro1.gts
import Component from '@glimmer/component';

interface ReproSignature {
  Element: HTMLDivElement;
  Args: {
  };
  Blocks: {
    default: [];
  };
}

export default class ReproComponent extends Component<ReproSignature> {
  <template>
    <div id="1" class="repro" ...attributes>
    </div>
  </template>
}
```

tested with `content-tag` v2.0.2 and v2.0.3, everything else updated to latest stable versions as of today.

Besides this, seems that `ember-eslint-parser` is broken on <template> parsing too, I will link the issue later.

**Comment by NullVoxPopuli** [comment]
can you provide the output of `pnpm why @glimmer/syntax` (or whatever the equiv is for your package manager)?

if you're pinning the version of `@glimmer/syntax`, that might be the problem.

**Comment by NullVoxPopuli** [comment]
does `yarn why @glimmer/syntax` show that ember-eslint-parser has the 0.92.x version?
not sure if that command needs to specify --depth or --recursive or anything like that, but the error persistent definitely _smells like_ yarn did something bad.

**Comment by NullVoxPopuli** [comment]
oh! can you try either of:
```bash
npx are-my-node-modules-messed-up
# or
npx dephellp
```

**Comment by NullVoxPopuli** [comment]
are you using prettier-plugin-ember-template-tag @ 2.0.2?

**Comment by vlascik** [comment]
> are you using prettier-plugin-ember-template-tag @ 2.0.2?

Yep. So, you were right, it was the messed up node_modules, the issue was that I had `content-tag` pinned to 2.0.3, but `prettier-plugin-ember-template-tag` only works with v1.x. 

Thanks for pointing me to `are-my-node-modules-messed-up`, that tool is awesome.

Will have to stop relying on `resolutions` so much... or switch to pnpm. Oh well.

Thank you again, I will close this issue.
